# Pré-processamento 3 - Estrutura silábica e revisão ortográfica

## Carregando a base tratada

In [4]:
# importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pandas.plotting import scatter_matrix
# importando o arquivo tratado
from pathlib import Path
df = pd.read_excel(
    Path("Corpus_SANTOS_TONI_FDC_tratado.xlsx")
)

df.head()

,PALAVRA,LEMA,CATMORF,TRANSCRICAO,ACENTUACAO,ESTSILABICA,CATACENTUAL,FREQ
0,que,que,Conjunção Subordinada,&ke%,&ke%,&CV%,mono,22627
1,é,ser,Verbo Principal Indicativo Presente Terceira P...,&5%,&5%,&V%,oxítona,17108
2,o,o,Determinante Artigo Masculino Singular,&o%,&o%,&V%,mono,16513
3,não,não,Advérbio Negativo,&nAW%,&n2W%,&CVG%,oxítona,11696
4,a,o,Determinante Artigo Feminino Singular,&a%,&a%,&V%,mono,10546

## Verificação das estruturas silábicas

In [5]:
# conta as estruturas silábicas mais frequentes
df['ESTSILABICA'].value_counts().head(20)

ESTSILABICA
&CV-CV-CV%          1126
&CV-CV%             1036
erro                 641
&CV-CV-CV-CV%        505
&CV-CVG%             328
&V-CV-CV%            244
&CV-CV-CVG%          201
&CV-CVS%             199
&CV-CV-CVS%          190
&CV-CVC%             182
&V-CV-CV-CV%         173
&V-CV%               172
&CVC-CV-CV%          172
&CVC-CV%             156
&CVG-CV%             154
&CCV-CV%             144
&CCV-CV-CV%          138
&CVG%                112
&CVG-CV-CV%          105
&CV-CV-CV-CV-CV%      91
Name: count, dtype: int64

In [6]:
# seleciona os registros cuja estrutura silábica foi classificada como erro
df_erros_silabicos = df[df['ESTSILABICA'] == 'erro']

# mostra algumas colunas para investigar esses registros
df_erros_silabicos[
    ['PALAVRA', 'LEMA', 'CATMORF', 'ESTSILABICA', 'CATACENTUAL', 'FREQ']
].head(20)

,PALAVRA,LEMA,CATMORF,ESTSILABICA,CATACENTUAL,FREQ
1405,m,m,Nome Própio Pessoa,erro,erro,18
1520,tua,teu,Determinante Possessivo Segunda Pessoa Feminin...,erro,erro,16
1521,uhhuh,uhhuh,Nome Própio Pessoa,erro,erro,16
1525,ah,ah,Interjeição,erro,erro,15
1546,creck,creck,Nome Própio Pessoa,erro,erro,15
1572,p,p,Nome Comun Masculino Singular,erro,erro,15
1581,po,po,Nome Comun Masculino Singular,erro,erro,15
1590,z,z,Nome Comun Masculino Singular,erro,erro,15
1593,ahhh,ahhh,Nome Própio Pessoa,erro,erro,14
1594,ãhn,ãhn,Nome Própio Pessoa,erro,erro,14
1600,at,at,Nome Própio Pessoa,erro,erro,14
1607,bum,bum,Nome Comun Masculino Singular,erro,erro,14
1621,ehm,ehm,Nome Própio Pessoa,erro,erro,14
1627,fio,fio,Nome Comun Masculino Singular,erro,erro,14
1636,han,han,Nome Própio Pessoa,erro,erro,14
1711,enh,enh,Nome Própio Pessoa,erro,erro,13
1726,meg,meg,Nome Própio Pessoa,erro,erro,13
1732,ow,ow,Interjeição,erro,erro,13
1748,tchum,tchum,Interjeição,erro,erro,13
1756,xo,xo,Advérbio Geral,erro,erro,13

In [8]:
df_erros_silabicos.shape

(641, 8)

In [9]:
df_erros_silabicos['CATMORF'].value_counts().head(20)

CATMORF
Nome Própio Pessoa                                                     425
Nome Comun Masculino Singular                                           62
Interjeição                                                             36
Nome Própio Organização                                                 19
Nome Comun Feminino Singular                                            15
Verbo Principal Indicativo Presente Terceira Pessoa Singular            12
Verbo Principal Indicativo Passado Terceira Pessoa Singular              8
Verbo Principal Indicativo Passado Primeira Pessoa Singular              5
Nome Própio Outros                                                       5
Nome Comun Masculino Plural                                              5
Advérbio Geral                                                           5
Nome Própio Lugar                                                        5
Conjunção Coordenada                                                     3
Adjetivo Qualificativo Comum Invariável                                  3
Adjetivo Qualificativo Masculino Singular                                3
Adjetivo Qualificativo Comum Singular                                    3
Preposição Preposição Simples                                            3
Quantidade                                                               2
Pronome Pessoal Segunda Pessoa Comum Singular Nominativo Indefinido      2
Pronome Pessoal Segunda Pessoa Comum Plural Indefinido                   2
Name: count, dtype: int64

In [10]:
categorias_excluir = [
    'Nome Própio Pessoa',
    'Nome Própio Organização',
    'Nome Própio Lugar',
    'Interjeição'
]

df_erros_comuns = df_erros_silabicos[
    ~df_erros_silabicos['CATMORF'].isin(categorias_excluir)
]

df_erros_comuns[
    ['PALAVRA', 'LEMA', 'CATMORF', 'FREQ']
].sort_values('FREQ', ascending=False).head(30)

     PALAVRA  LEMA                                            CATMORF  FREQ
1520     tua   teu  Determinante Possessivo Segunda Pessoa Feminin...    16
1572       p     p                      Nome Comun Masculino Singular    15
1581      po    po                      Nome Comun Masculino Singular    15
1590       z     z                      Nome Comun Masculino Singular    15
1607     bum   bum                      Nome Comun Masculino Singular    14
1627     fio   fio                      Nome Comun Masculino Singular    14
1756      xo    xo                                     Advérbio Geral    13
1766     bim   bim                                     Advérbio Geral    12
1798       g     g                      Nome Comun Masculino Singular    12
1823     pia   pia                       Nome Comun Feminino Singular    12
1845       y     y                                 Nome Própio Outros    12
1921      nã    nã                                     Advérbio Geral    11
1932      pi    pi                      Nome Comun Masculino Singular    11
1934     pim   pim                      Nome Comun Masculino Singular    11
1950    show  show                      Nome Comun Masculino Singular    11
1987      bu    bu  Verbo Principal Indicativo Passado Terceira Pe...    10
1988      ca    ca                               Conjunção Coordenada    10
2198      mu    mu                      Nome Comun Masculino Singular     9
2265    book  book                      Nome Comun Masculino Singular     8
2329      in    in                      Preposição Preposição Simples     8
2330       j     j                      Nome Comun Masculino Singular     8
2381       s     s                      Nome Comun Masculino Singular     8
2394     two   two                      Nome Comun Masculino Singular     8
2408      vo   vos  Pronome Pessoal Segunda Pessoa Comum Plural In...     8
2410       w     w                      Nome Comun Masculino Singular     8
2529     lhe   lhe  Pronome Pessoal Terceira Pessoa Comum Singular...     7
2593    prum  prum                      Nome Comun Masculino Singular     7
2595       q     q                      Nome Comun Masculino Singular     7
2601      ri   rir  Verbo Principal Indicativo Passado Primeira Pe...     7
2618      ss     s                        Nome Comun Masculino Plural     7

In [11]:
df_erros_silabicos['PALAVRA'].nunique()

585

In [13]:
# remove os registros sem estrutura silábica válida
df = df[df['ESTSILABICA'] != 'erro']

# verifica o novo tamanho da base
df.shape

(10863, 8)

In [14]:
df.to_excel("Corpus_SANTOS_TONI_FDC_tratado.xlsx", index=False)